import React from 'react'
import Navbar from '@/src/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <head>
        {/* You can import Google Fonts directly into your CSS file */}
      </head>
      <body className={inter.className}>
        <header>
          {/* Navbar Component */}
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;