import React from 'react'
<<<<<<< HEAD
import Navbar from '@/src/components/Navbar'
=======
import Navbar from './components/Navbar'
>>>>>>> ced081341288af4d59f2486683f859c905c14d99
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
<<<<<<< HEAD
=======
      <head>
        {/* You can import Google Fonts directly into your CSS file */}
      </head>
>>>>>>> ced081341288af4d59f2486683f859c905c14d99
      <body className={inter.className}>
        <header>
          {/* Navbar Component */}
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
};

<<<<<<< HEAD
export default RootLayout;
=======
export default RootLayout;
>>>>>>> ced081341288af4d59f2486683f859c905c14d99
